import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/sidebar'
import { Navbar } from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="h-full relative">
            <div className="hidden h-full md:flex md:w-72 md:flex-col 
            md:fixed md:inset-y-0 bg-[#19191a]">
                <div>
                    <Sidebar />
                </div>
            </div>
            <main className="md:pl-72">
                <Navbar/>
                {children}
            </main>
        </div>
  )
}
